apiVersion: v1
kind: Service
metadata:
  name: stock
  labels:
    app: stock
spec:
  type: NodePort
  ports:
    - port: 8081
      name: stock
  selector:
    app: stock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: cubas/stock:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_RABBITMQ_HOST
              value: falling-grasshopper-rabbitmq